/***************************************************************
 * This file is automatically generated.
 ***************************************************************/

#include "pebble_os.h"
#include "pebble_app.h"
#include "pebble_fonts.h"

// Undefine some macros so our typedefs don't get confused.
#undef GPoint(x, y)
#undef GSize(w, h)
#undef GRect(x, y, w, h)

#include "claypellet.h"



t_animation_init_cb animation_init_cb;
t_animation_set_delay_cb animation_set_delay_cb;
t_animation_set_duration_cb animation_set_duration_cb;
t_animation_set_curve_cb animation_set_curve_cb;
t_animation_set_handlers_cb animation_set_handlers_cb;
t_animation_set_implementation_cb animation_set_implementation_cb;
t_animation_get_context_cb animation_get_context_cb;
t_animation_schedule_cb animation_schedule_cb;
t_animation_unschedule_cb animation_unschedule_cb;
t_animation_unschedule_all_cb animation_unschedule_all_cb;
t_animation_is_scheduled_cb animation_is_scheduled_cb;
t_property_animation_init_layer_frame_cb property_animation_init_layer_frame_cb;
t_app_event_loop_cb app_event_loop_cb;
t_bmp_init_container_cb bmp_init_container_cb;
t_bmp_deinit_container_cb bmp_deinit_container_cb;
t_graphics_draw_bitmap_in_rect_cb graphics_draw_bitmap_in_rect_cb;
t_rotbmp_deinit_container_cb rotbmp_deinit_container_cb;
t_rotbmp_init_container_cb rotbmp_init_container_cb;
t_rotbmp_pair_deinit_container_cb rotbmp_pair_deinit_container_cb;
t_rotbmp_pair_init_container_cb rotbmp_pair_init_container_cb;
t_rotbmp_pair_layer_set_src_ic_cb rotbmp_pair_layer_set_src_ic_cb;
t_rotbmp_pair_layer_set_angle_cb rotbmp_pair_layer_set_angle_cb;
t_app_get_current_graphics_context_cb app_get_current_graphics_context_cb;
t_graphics_draw_pixel_cb graphics_draw_pixel_cb;
t_graphics_draw_line_cb graphics_draw_line_cb;
t_graphics_fill_rect_cb graphics_fill_rect_cb;
t_graphics_draw_circle_cb graphics_draw_circle_cb;
t_graphics_fill_circle_cb graphics_fill_circle_cb;
t_graphics_draw_round_rect_cb graphics_draw_round_rect_cb;
t_gpath_init_cb gpath_init_cb;
t_gpath_move_to_cb gpath_move_to_cb;
t_gpath_rotate_to_cb gpath_rotate_to_cb;
t_gpath_draw_outline_cb gpath_draw_outline_cb;
t_gpath_draw_filled_cb gpath_draw_filled_cb;
t_graphics_context_set_stroke_color_cb graphics_context_set_stroke_color_cb;
t_graphics_context_set_fill_color_cb graphics_context_set_fill_color_cb;
t_graphics_context_set_text_color_cb graphics_context_set_text_color_cb;
t_graphics_context_set_compositing_mode_cb graphics_context_set_compositing_mode_cb;
t_graphics_text_draw_cb graphics_text_draw_cb;
t_light_enable_cb light_enable_cb;
t_light_enable_interaction_cb light_enable_interaction_cb;
t_window_set_click_config_provider_cb window_set_click_config_provider_cb;
t_vibes_double_pulse_cb vibes_double_pulse_cb;
t_vibes_enqueue_custom_pattern_cb vibes_enqueue_custom_pattern_cb;
t_vibes_long_pulse_cb vibes_long_pulse_cb;
t_vibes_short_pulse_cb vibes_short_pulse_cb;
t_layer_mark_dirty_cb layer_mark_dirty_cb;
t_layer_remove_from_parent_cb layer_remove_from_parent_cb;
t_layer_add_child_cb layer_add_child_cb;
t_layer_get_frame_cb layer_get_frame_cb;
t_layer_set_frame_cb layer_set_frame_cb;
t_layer_set_hidden_cb layer_set_hidden_cb;
t_layer_init_cb layer_init_cb;
t_cos_lookup_cb cos_lookup_cb;
t_sin_lookup_cb sin_lookup_cb;
t_grect_center_point_cb grect_center_point_cb;
t_resource_init_current_app_cb resource_init_current_app_cb;
t_resource_get_handle_cb resource_get_handle_cb;
t_resource_load_cb resource_load_cb;
t_resource_load_byte_range_cb resource_load_byte_range_cb;
t_resource_size_cb resource_size_cb;
t_fonts_get_system_font_cb fonts_get_system_font_cb;
t_fonts_load_custom_font_cb fonts_load_custom_font_cb;
t_fonts_unload_custom_font_cb fonts_unload_custom_font_cb;
t_text_layer_init_cb text_layer_init_cb;
t_text_layer_get_text_cb text_layer_get_text_cb;
t_text_layer_set_text_cb text_layer_set_text_cb;
t_text_layer_set_background_color_cb text_layer_set_background_color_cb;
t_text_layer_set_font_cb text_layer_set_font_cb;
t_text_layer_set_text_alignment_cb text_layer_set_text_alignment_cb;
t_text_layer_set_text_color_cb text_layer_set_text_color_cb;
t_clock_is_24h_style_cb clock_is_24h_style_cb;
t_get_time_cb get_time_cb;
t_string_format_time_cb string_format_time_cb;
t_psleep_cb psleep_cb;
t_app_timer_send_event_cb app_timer_send_event_cb;
t_app_timer_cancel_event_cb app_timer_cancel_event_cb;
t_window_init_cb window_init_cb;
t_window_stack_push_cb window_stack_push_cb;
t_window_set_background_color_cb window_set_background_color_cb;
t_window_render_cb window_render_cb;
t_window_set_fullscreen_cb window_set_fullscreen_cb;

void setup_callbacks(t_animation_init_cb animation_init,
                     t_animation_set_delay_cb animation_set_delay,
                     t_animation_set_duration_cb animation_set_duration,
                     t_animation_set_curve_cb animation_set_curve,
                     t_animation_set_handlers_cb animation_set_handlers,
                     t_animation_set_implementation_cb animation_set_implementation,
                     t_animation_get_context_cb animation_get_context,
                     t_animation_schedule_cb animation_schedule,
                     t_animation_unschedule_cb animation_unschedule,
                     t_animation_unschedule_all_cb animation_unschedule_all,
                     t_animation_is_scheduled_cb animation_is_scheduled,
                     t_property_animation_init_layer_frame_cb property_animation_init_layer_frame,
                     t_app_event_loop_cb app_event_loop,
                     t_bmp_init_container_cb bmp_init_container,
                     t_bmp_deinit_container_cb bmp_deinit_container,
                     t_graphics_draw_bitmap_in_rect_cb graphics_draw_bitmap_in_rect,
                     t_rotbmp_deinit_container_cb rotbmp_deinit_container,
                     t_rotbmp_init_container_cb rotbmp_init_container,
                     t_rotbmp_pair_deinit_container_cb rotbmp_pair_deinit_container,
                     t_rotbmp_pair_init_container_cb rotbmp_pair_init_container,
                     t_rotbmp_pair_layer_set_src_ic_cb rotbmp_pair_layer_set_src_ic,
                     t_rotbmp_pair_layer_set_angle_cb rotbmp_pair_layer_set_angle,
                     t_app_get_current_graphics_context_cb app_get_current_graphics_context,
                     t_graphics_draw_pixel_cb graphics_draw_pixel,
                     t_graphics_draw_line_cb graphics_draw_line,
                     t_graphics_fill_rect_cb graphics_fill_rect,
                     t_graphics_draw_circle_cb graphics_draw_circle,
                     t_graphics_fill_circle_cb graphics_fill_circle,
                     t_graphics_draw_round_rect_cb graphics_draw_round_rect,
                     t_gpath_init_cb gpath_init,
                     t_gpath_move_to_cb gpath_move_to,
                     t_gpath_rotate_to_cb gpath_rotate_to,
                     t_gpath_draw_outline_cb gpath_draw_outline,
                     t_gpath_draw_filled_cb gpath_draw_filled,
                     t_graphics_context_set_stroke_color_cb graphics_context_set_stroke_color,
                     t_graphics_context_set_fill_color_cb graphics_context_set_fill_color,
                     t_graphics_context_set_text_color_cb graphics_context_set_text_color,
                     t_graphics_context_set_compositing_mode_cb graphics_context_set_compositing_mode,
                     t_graphics_text_draw_cb graphics_text_draw,
                     t_light_enable_cb light_enable,
                     t_light_enable_interaction_cb light_enable_interaction,
                     t_window_set_click_config_provider_cb window_set_click_config_provider,
                     t_vibes_double_pulse_cb vibes_double_pulse,
                     t_vibes_enqueue_custom_pattern_cb vibes_enqueue_custom_pattern,
                     t_vibes_long_pulse_cb vibes_long_pulse,
                     t_vibes_short_pulse_cb vibes_short_pulse,
                     t_layer_mark_dirty_cb layer_mark_dirty,
                     t_layer_remove_from_parent_cb layer_remove_from_parent,
                     t_layer_add_child_cb layer_add_child,
                     t_layer_get_frame_cb layer_get_frame,
                     t_layer_set_frame_cb layer_set_frame,
                     t_layer_set_hidden_cb layer_set_hidden,
                     t_layer_init_cb layer_init,
                     t_cos_lookup_cb cos_lookup,
                     t_sin_lookup_cb sin_lookup,
                     t_grect_center_point_cb grect_center_point,
                     t_resource_init_current_app_cb resource_init_current_app,
                     t_resource_get_handle_cb resource_get_handle,
                     t_resource_load_cb resource_load,
                     t_resource_load_byte_range_cb resource_load_byte_range,
                     t_resource_size_cb resource_size,
                     t_fonts_get_system_font_cb fonts_get_system_font,
                     t_fonts_load_custom_font_cb fonts_load_custom_font,
                     t_fonts_unload_custom_font_cb fonts_unload_custom_font,
                     t_text_layer_init_cb text_layer_init,
                     t_text_layer_get_text_cb text_layer_get_text,
                     t_text_layer_set_text_cb text_layer_set_text,
                     t_text_layer_set_background_color_cb text_layer_set_background_color,
                     t_text_layer_set_font_cb text_layer_set_font,
                     t_text_layer_set_text_alignment_cb text_layer_set_text_alignment,
                     t_text_layer_set_text_color_cb text_layer_set_text_color,
                     t_clock_is_24h_style_cb clock_is_24h_style,
                     t_get_time_cb get_time,
                     t_string_format_time_cb string_format_time,
                     t_psleep_cb psleep,
                     t_app_timer_send_event_cb app_timer_send_event,
                     t_app_timer_cancel_event_cb app_timer_cancel_event,
                     t_window_init_cb window_init,
                     t_window_stack_push_cb window_stack_push,
                     t_window_set_background_color_cb window_set_background_color,
                     t_window_render_cb window_render,
                     t_window_set_fullscreen_cb window_set_fullscreen) {
    animation_init_cb = animation_init;
    animation_set_delay_cb = animation_set_delay;
    animation_set_duration_cb = animation_set_duration;
    animation_set_curve_cb = animation_set_curve;
    animation_set_handlers_cb = animation_set_handlers;
    animation_set_implementation_cb = animation_set_implementation;
    animation_get_context_cb = animation_get_context;
    animation_schedule_cb = animation_schedule;
    animation_unschedule_cb = animation_unschedule;
    animation_unschedule_all_cb = animation_unschedule_all;
    animation_is_scheduled_cb = animation_is_scheduled;
    property_animation_init_layer_frame_cb = property_animation_init_layer_frame;
    app_event_loop_cb = app_event_loop;
    bmp_init_container_cb = bmp_init_container;
    bmp_deinit_container_cb = bmp_deinit_container;
    graphics_draw_bitmap_in_rect_cb = graphics_draw_bitmap_in_rect;
    rotbmp_deinit_container_cb = rotbmp_deinit_container;
    rotbmp_init_container_cb = rotbmp_init_container;
    rotbmp_pair_deinit_container_cb = rotbmp_pair_deinit_container;
    rotbmp_pair_init_container_cb = rotbmp_pair_init_container;
    rotbmp_pair_layer_set_src_ic_cb = rotbmp_pair_layer_set_src_ic;
    rotbmp_pair_layer_set_angle_cb = rotbmp_pair_layer_set_angle;
    app_get_current_graphics_context_cb = app_get_current_graphics_context;
    graphics_draw_pixel_cb = graphics_draw_pixel;
    graphics_draw_line_cb = graphics_draw_line;
    graphics_fill_rect_cb = graphics_fill_rect;
    graphics_draw_circle_cb = graphics_draw_circle;
    graphics_fill_circle_cb = graphics_fill_circle;
    graphics_draw_round_rect_cb = graphics_draw_round_rect;
    gpath_init_cb = gpath_init;
    gpath_move_to_cb = gpath_move_to;
    gpath_rotate_to_cb = gpath_rotate_to;
    gpath_draw_outline_cb = gpath_draw_outline;
    gpath_draw_filled_cb = gpath_draw_filled;
    graphics_context_set_stroke_color_cb = graphics_context_set_stroke_color;
    graphics_context_set_fill_color_cb = graphics_context_set_fill_color;
    graphics_context_set_text_color_cb = graphics_context_set_text_color;
    graphics_context_set_compositing_mode_cb = graphics_context_set_compositing_mode;
    graphics_text_draw_cb = graphics_text_draw;
    light_enable_cb = light_enable;
    light_enable_interaction_cb = light_enable_interaction;
    window_set_click_config_provider_cb = window_set_click_config_provider;
    vibes_double_pulse_cb = vibes_double_pulse;
    vibes_enqueue_custom_pattern_cb = vibes_enqueue_custom_pattern;
    vibes_long_pulse_cb = vibes_long_pulse;
    vibes_short_pulse_cb = vibes_short_pulse;
    layer_mark_dirty_cb = layer_mark_dirty;
    layer_remove_from_parent_cb = layer_remove_from_parent;
    layer_add_child_cb = layer_add_child;
    layer_get_frame_cb = layer_get_frame;
    layer_set_frame_cb = layer_set_frame;
    layer_set_hidden_cb = layer_set_hidden;
    layer_init_cb = layer_init;
    cos_lookup_cb = cos_lookup;
    sin_lookup_cb = sin_lookup;
    grect_center_point_cb = grect_center_point;
    resource_init_current_app_cb = resource_init_current_app;
    resource_get_handle_cb = resource_get_handle;
    resource_load_cb = resource_load;
    resource_load_byte_range_cb = resource_load_byte_range;
    resource_size_cb = resource_size;
    fonts_get_system_font_cb = fonts_get_system_font;
    fonts_load_custom_font_cb = fonts_load_custom_font;
    fonts_unload_custom_font_cb = fonts_unload_custom_font;
    text_layer_init_cb = text_layer_init;
    text_layer_get_text_cb = text_layer_get_text;
    text_layer_set_text_cb = text_layer_set_text;
    text_layer_set_background_color_cb = text_layer_set_background_color;
    text_layer_set_font_cb = text_layer_set_font;
    text_layer_set_text_alignment_cb = text_layer_set_text_alignment;
    text_layer_set_text_color_cb = text_layer_set_text_color;
    clock_is_24h_style_cb = clock_is_24h_style;
    get_time_cb = get_time;
    string_format_time_cb = string_format_time;
    psleep_cb = psleep;
    app_timer_send_event_cb = app_timer_send_event;
    app_timer_cancel_event_cb = app_timer_cancel_event;
    window_init_cb = window_init;
    window_stack_push_cb = window_stack_push;
    window_set_background_color_cb = window_set_background_color;
    window_render_cb = window_render;
    window_set_fullscreen_cb = window_set_fullscreen;
}

void animation_init(Animation *animation) { animation_init_cb(animation); }
void animation_set_delay(Animation *animation, uint32_t delay_ms) { animation_set_delay_cb(animation, delay_ms); }
void animation_set_duration(Animation *animation, uint32_t duration_ms) { animation_set_duration_cb(animation, duration_ms); }
void animation_set_curve(Animation *animation, AnimationCurve curve) { animation_set_curve_cb(animation, curve); }
void animation_set_handlers(Animation *animation, AnimationHandlers callbacks, void *context) { animation_set_handlers_cb(animation, callbacks, context); }
void animation_set_implementation(Animation *animation, const AnimationImplementation *implementation) { animation_set_implementation_cb(animation, implementation); }
void *animation_get_context(Animation *animation) { return animation_get_context_cb(animation); }
void animation_schedule(Animation *animation) { animation_schedule_cb(animation); }
void animation_unschedule(Animation *animation) { animation_unschedule_cb(animation); }
void animation_unschedule_all(void) { animation_unschedule_all_cb(); }
bool animation_is_scheduled(Animation *animation) { return animation_is_scheduled_cb(animation); }
void property_animation_init_layer_frame(PropertyAnimation *property_animation, struct Layer *layer, GRect *from_frame, GRect *to_frame) { property_animation_init_layer_frame_cb(property_animation, layer, from_frame, to_frame); }
void app_event_loop(AppTaskContextRef app_task_ctx, PebbleAppHandlers *handlers) { app_event_loop_cb(app_task_ctx, handlers); }
bool bmp_init_container(int resource_id, BmpContainer *c) { return bmp_init_container_cb(resource_id, c); }
void bmp_deinit_container(BmpContainer *c) { bmp_deinit_container_cb(c); }
void graphics_draw_bitmap_in_rect(GContext *ctx, const GBitmap *bitmap, GRect rect) { graphics_draw_bitmap_in_rect_cb(ctx, bitmap, rect); }
void rotbmp_deinit_container(RotBmpContainer *c) { rotbmp_deinit_container_cb(c); }
bool rotbmp_init_container(int resource_id, RotBmpContainer *c) { return rotbmp_init_container_cb(resource_id, c); }
void rotbmp_pair_deinit_container(RotBmpPairContainer *c) { rotbmp_pair_deinit_container_cb(c); }
bool rotbmp_pair_init_container(int white_resource_id, int black_resource_id, RotBmpPairContainer *c) { return rotbmp_pair_init_container_cb(white_resource_id, black_resource_id, c); }
void rotbmp_pair_layer_set_src_ic(RotBmpPairLayer *pair, GPoint ic) { rotbmp_pair_layer_set_src_ic_cb(pair, ic); }
void rotbmp_pair_layer_set_angle(RotBmpPairLayer *pair, int32_t angle) { rotbmp_pair_layer_set_angle_cb(pair, angle); }
GContext *app_get_current_graphics_context(void) { return app_get_current_graphics_context_cb(); }
void graphics_draw_pixel(GContext *ctx, GPoint point) { graphics_draw_pixel_cb(ctx, point); }
void graphics_draw_line(GContext *ctx, GPoint p0, GPoint p1) { graphics_draw_line_cb(ctx, p0, p1); }
void graphics_fill_rect(GContext *ctx, GRect rect, uint8_t corner_radius, GCornerMask corner_mask) { graphics_fill_rect_cb(ctx, rect, corner_radius, corner_mask); }
void graphics_draw_circle(GContext *ctx, GPoint p, int radius) { graphics_draw_circle_cb(ctx, p, radius); }
void graphics_fill_circle(GContext *ctx, GPoint p, int radius) { graphics_fill_circle_cb(ctx, p, radius); }
void graphics_draw_round_rect(GContext *ctx, GRect rect, int radius) { graphics_draw_round_rect_cb(ctx, rect, radius); }
void gpath_init(GPath *path, const GPathInfo *init) { gpath_init_cb(path, init); }
void gpath_move_to(GPath *path, GPoint point) { gpath_move_to_cb(path, point); }
void gpath_rotate_to(GPath *path, int32_t angle) { gpath_rotate_to_cb(path, angle); }
void gpath_draw_outline(GContext *ctx, GPath *path) { gpath_draw_outline_cb(ctx, path); }
void gpath_draw_filled(GContext *ctx, GPath *path) { gpath_draw_filled_cb(ctx, path); }
void graphics_context_set_stroke_color(GContext *ctx, GColor color) { graphics_context_set_stroke_color_cb(ctx, color); }
void graphics_context_set_fill_color(GContext *ctx, GColor color) { graphics_context_set_fill_color_cb(ctx, color); }
void graphics_context_set_text_color(GContext *ctx, GColor color) { graphics_context_set_text_color_cb(ctx, color); }
void graphics_context_set_compositing_mode(GContext *ctx, GCompOp mode) { graphics_context_set_compositing_mode_cb(ctx, mode); }
void graphics_text_draw(GContext *ctx, const char *text, const GFont font, const GRect box, const GTextOverflowMode overflow_mode, const GTextAlignment alignment, const GTextLayoutCacheRef layout) { graphics_text_draw_cb(ctx, text, font, box, overflow_mode, alignment, layout); }
void light_enable(bool enable) { light_enable_cb(enable); }
void light_enable_interaction(void) { light_enable_interaction_cb(); }
void window_set_click_config_provider(Window *window, ClickConfigProvider click_config_provider) { window_set_click_config_provider_cb(window, click_config_provider); }
void vibes_double_pulse(void) { vibes_double_pulse_cb(); }
void vibes_enqueue_custom_pattern(VibePattern pattern) { vibes_enqueue_custom_pattern_cb(pattern); }
void vibes_long_pulse(void) { vibes_long_pulse_cb(); }
void vibes_short_pulse(void) { vibes_short_pulse_cb(); }
void layer_mark_dirty(Layer *layer) { layer_mark_dirty_cb(layer); }
void layer_remove_from_parent(Layer *child) { layer_remove_from_parent_cb(child); }
void layer_add_child(Layer *parent, Layer *child) { layer_add_child_cb(parent, child); }
GRect layer_get_frame(Layer *layer) { return layer_get_frame_cb(layer); }
void layer_set_frame(Layer *layer, GRect frame) { layer_set_frame_cb(layer, frame); }
void layer_set_hidden(Layer *layer, bool hidden) { layer_set_hidden_cb(layer, hidden); }
void layer_init(Layer *layer, GRect frame) { layer_init_cb(layer, frame); }
int32_t cos_lookup(int32_t angle) { return cos_lookup_cb(angle); }
int32_t sin_lookup(int32_t angle) { return sin_lookup_cb(angle); }
GPoint grect_center_point(GRect *rect) { return grect_center_point_cb(rect); }
void resource_init_current_app(ResVersionHandle version) { resource_init_current_app_cb(version); }
ResHandle resource_get_handle(uint32_t file_id) { return resource_get_handle_cb(file_id); }
size_t resource_load(ResHandle h, uint8_t *buffer, size_t max_length) { return resource_load_cb(h, buffer, max_length); }
size_t resource_load_byte_range(ResHandle h, uint32_t start_bytes, uint8_t *data, size_t num_bytes) { return resource_load_byte_range_cb(h, start_bytes, data, num_bytes); }
size_t resource_size(ResHandle h) { return resource_size_cb(h); }
GFont fonts_get_system_font(const char *font_key) { return fonts_get_system_font_cb(font_key); }
GFont fonts_load_custom_font(ResHandle resource) { return fonts_load_custom_font_cb(resource); }
void fonts_unload_custom_font(GFont font) { fonts_unload_custom_font_cb(font); }
void text_layer_init(TextLayer *text_layer, GRect frame) { text_layer_init_cb(text_layer, frame); }
const char *text_layer_get_text(TextLayer *text_layer) { return text_layer_get_text_cb(text_layer); }
void text_layer_set_text(TextLayer *text_layer, const char *text) { text_layer_set_text_cb(text_layer, text); }
void text_layer_set_background_color(TextLayer *text_layer, GColor color) { text_layer_set_background_color_cb(text_layer, color); }
void text_layer_set_font(TextLayer *text_layer, GFont font) { text_layer_set_font_cb(text_layer, font); }
void text_layer_set_text_alignment(TextLayer *text_layer, GTextAlignment text_alignment) { text_layer_set_text_alignment_cb(text_layer, text_alignment); }
void text_layer_set_text_color(TextLayer *text_layer, GColor color) { text_layer_set_text_color_cb(text_layer, color); }
bool clock_is_24h_style(void) { return clock_is_24h_style_cb(); }
void get_time(PblTm *time) { get_time_cb(time); }
void string_format_time(char *ptr, size_t maxsize, const char *format, const PblTm *timeptr) { string_format_time_cb(ptr, maxsize, format, timeptr); }
void psleep(int millis) { psleep_cb(millis); }
AppTimerHandle app_timer_send_event(AppContextRef app_ctx, uint32_t timeout_ms, uint32_t cookie) { return app_timer_send_event_cb(app_ctx, timeout_ms, cookie); }
bool app_timer_cancel_event(AppContextRef app_ctx_ref, AppTimerHandle handle) { return app_timer_cancel_event_cb(app_ctx_ref, handle); }
void window_init(Window *window, const char *debug_name) { window_init_cb(window, debug_name); }
void window_stack_push(Window *window, bool animated) { window_stack_push_cb(window, animated); }
void window_set_background_color(Window *window, GColor background_color) { window_set_background_color_cb(window, background_color); }
void window_render(Window *window, GContext *ctx) { window_render_cb(window, ctx); }
void window_set_fullscreen(Window *window, bool enabled) { window_set_fullscreen_cb(window, enabled); }

